<?php
session_start();
if (isset($_SESSION['id'])) {
    session_destroy();
}

if (empty($_SESSION['id'])) {
    header('Refresh: 2; URL=index.html'); // Delay for 2 seconds to allow the animation to play
    echo '<!DOCTYPE html>
    <html lang="bg">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Logging Out...</title>
      <link rel="stylesheet" href="../css/logout.css" />
      <link rel="preconnect" href="https://fonts.googleapis.com/" />
      <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"
        rel="stylesheet"
      />
    </head>
    <body>
        <div class="logout-animation">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200" height="200" style="shape-rendering: auto; display: block; background: rgb(13, 27, 30);"><g><path style="transform:scale(0.76);transform-origin:50px 50px" stroke-linecap="round" d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z" stroke-dasharray="156.51924621582032 100.06968200683593" stroke-width="11" stroke="#e78207" fill="none">
            <animate values="0;256.58892822265625" keyTimes="0;1" dur="1s" repeatCount="indefinite" attributeName="stroke-dashoffset"/>
          </path><g/></g><!-- [ldio] generated by https://loading.io --></svg>
          <p style="color: #f1f0cc;">Излизане от профила</p>
        </div>
    </body>
    </html>';
    exit();
}
